### ISSUE TITLE
[Bug] idk how to fix

### ISSUE THREAD

**Issue by IGNzHalo** [DaddyImPregnant/Atlantic#1]
[09:19:15 INFO]: [Atlantic] Enabling Atlantic v1.0.2-SNAPSHOT
[09:19:15 ERROR]: Error occurred while enabling Atlantic v1.0.2-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
    at me.scifi.hcf.visualise.ProtocolLibHook.hook(ProtocolLibHook.java:40) ~[?:?]
    at me.scifi.hcf.HCF.onEnable(HCF.java:133) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:?]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:477) [spigot.jar:?]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:395) [spigot.jar:?]
    at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354) [spigot.jar:?]
    at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328) [spigot.jar:?]
    at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284) [spigot.jar:?]
    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:232) [spigot.jar:?]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:495) [spigot.jar:?]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:?]

**Comment by BrianGrug** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server info (please complete the following information):**
 - Server version: [e.g. 1.7.10-SNAPSHOT]
 - Jar type [e.g. Exospigot]
 - Atlantic version [e.g. 1.0.3-SNAPSHOT]

**Additional context**
Add any other context about the problem here.

**Comment by BrianGrug** [comment]
As well as do /pl and see if ProtocolLib is enabled. If not, check console for errors.

**Comment by IGNzHalo** [comment]
that is the error LMAO

**Comment by BrianGrug** [comment]
I mean ProtocolLib errors

**Comment by UberDevo** [comment]
Using wrong version of protocollib @DaddyImPregnant

**Comment by BrianGrug** [comment]
Figured. Solved
